# Generated by Django 3.2.16 on 2023-04-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_num', models.CharField(max_length=50)),
                ('qr_code', models.FileField(upload_to='assets/QR')),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_ID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
    ]
